name: Node.js Package

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: publish
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Use Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.TS_EXPECT_ERROR_VALIDATOR_NPM_TOKEN }}
